version: '3.3'
services:
  database:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"
  wordpress-master:
    image: wordpress-development
    build: .
    container_name: wordpress-development-master
    environment:
      - WORDPRESS_DB_HOST=$WORDPRESS_DB_HOST
      - WORDPRESS_DATABASE_NAME=$WORDPRESS_DATABASE_NAME
      - WORDPRESS_DATABASE_USER=$WORDPRESS_DATABASE_NAME
      - WORDPRESS_DB_PASSWORD=$WORDPRESS_DB_PASSWORD
      - WORDPRESS_CONFIG_EXTRA=define('WP_CONTENT_URL', 'http://localhost:81/wp-content');
      - CONTAINER_MODE=$CONTAINER_MODE_MASTER
    ports:
      - "81:80"
    command: supervisord --nodaemon -c /etc/supervisor/supervisord.conf
  wordpress-slave:
    image: wordpress-development
    build: .
    container_name: wordpress-development-slave
    environment:
      - WORDPRESS_DB_HOST=$WORDPRESS_DB_HOST
      - WORDPRESS_DATABASE_NAME=$WORDPRESS_DATABASE_NAME
      - WORDPRESS_DATABASE_USER=$WORDPRESS_DATABASE_USER
      - WORDPRESS_DB_PASSWORD=$WORDPRESS_DB_PASSWORD
      - WORDPRESS_CONFIG_EXTRA=define('WP_CONTENT_URL', 'http://localhost:82/wp-content');
      - CONTAINER_MODE=$CONTAINER_MODE_SLAVE
      - RSYNC_WORDPRESS_MASTER=$RSYNC_WORDPRESS_MASTER
    ports:
      - "82:80"
    command: supervisord --nodaemon -c /etc/supervisor/supervisord.conf